// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7gN1cgYlun8Ypikoeq9IioRUB46Jv-A',
    appId: '1:765920319608:web:2c7eb6047a39533f41b58d',
    messagingSenderId: '765920319608',
    projectId: 'prakflutterfirebase-8ad27',
    authDomain: 'prakflutterfirebase-8ad27.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-8ad27.appspot.com',
    measurementId: 'G-76VW62EXBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWMHOSUd6D062K_iu2_jfAMrkMiH6a_ns',
    appId: '1:765920319608:android:61a4d576afd9d11341b58d',
    messagingSenderId: '765920319608',
    projectId: 'prakflutterfirebase-8ad27',
    storageBucket: 'prakflutterfirebase-8ad27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSTRRmYtuIQoKfqsQCku-n0oQVSNKUdA',
    appId: '1:765920319608:ios:4ced1a15925dee9b41b58d',
    messagingSenderId: '765920319608',
    projectId: 'prakflutterfirebase-8ad27',
    storageBucket: 'prakflutterfirebase-8ad27.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSTRRmYtuIQoKfqsQCku-n0oQVSNKUdA',
    appId: '1:765920319608:ios:4ced1a15925dee9b41b58d',
    messagingSenderId: '765920319608',
    projectId: 'prakflutterfirebase-8ad27',
    storageBucket: 'prakflutterfirebase-8ad27.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7gN1cgYlun8Ypikoeq9IioRUB46Jv-A',
    appId: '1:765920319608:web:ff391e6210e7408641b58d',
    messagingSenderId: '765920319608',
    projectId: 'prakflutterfirebase-8ad27',
    authDomain: 'prakflutterfirebase-8ad27.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-8ad27.appspot.com',
    measurementId: 'G-GW9284HQ0F',
  );
}
